language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode7.3
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
- Rscript -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    secure: dafV0ErhpPQlsTk3JGug7k3NclItCz2IGX9Zoq/KPJYGR7qjERPV2zie1DLozLVZRoXzIiqE5K9r37FkB3rWv/qvmRzYhS+ioqXWng2hqO4VWQ9fcvV0JVqva7ZRssyz7BcLBxRJ/ICDcOAzAZ6RohPDQLRQlKjj1GkNS0DalK0=
